/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myticketing;

import static java.lang.System.exit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FAIZAL
 */
public class addJadwal extends javax.swing.JFrame {
    public ResultSet res;
    public PreparedStatement ps;
    String timer, tanggal;
    String film_id;
    String id_auditorium;
    /**
     * Creates new form addJadwal
     */
    private void empty(){
        times.setText("");
        dates.setText("");
    }
    
    public addJadwal() {
        initComponents();
        addAudi();
        addFilm();
        load_table();
        filmTable();
    }
    
    private void load_table(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id Jadwal");
        model.addColumn("Id Film");
        model.addColumn("Id Audi");
        model.addColumn("Jam");
        model.addColumn("Tanggal");

        
        try{
          int i = 1;
          String sql = "SELECT * FROM schedule";
          java.sql.Connection conn = (Connection)config.configDB();
          java.sql.Statement stm = conn.createStatement();
          java.sql.ResultSet res = stm.executeQuery(sql);
          
          while(res.next()){
              model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5)});
          }
          
          jadwalTable.setModel(model);
        } catch (Exception e){
            
        }
          
    }
    
    private void filmTable(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id Film");
        model.addColumn("Judul");
        
        try{
          int i = 1;
          String sql = "SELECT * FROM film";
          java.sql.Connection conn = (Connection)config.configDB();
          java.sql.Statement stm = conn.createStatement();
          java.sql.ResultSet res = stm.executeQuery(sql);
          
          while(res.next()){
              model.addRow(new Object[]{res.getString(1), res.getString(2)});
          }
          
          filmTable.setModel(model);
        } catch (Exception e){
            
        }
    }
    
    private void addAudi() {
        String sql = "Select no_audi from auditorium";
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/selfticket_bioskop", "root", "");
            ps = con.prepareStatement(sql);
            res = ps.executeQuery(sql);
            while(res.next()){
                auditorium.addItem(res.getString("no_audi"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(addFilm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
        private void addFilm() {
        String sql = "Select * from film";
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/selfticket_bioskop", "root", "");
            ps = con.prepareStatement(sql);
            res = ps.executeQuery(sql);
            while(res.next()){
                film_judul.addItem(res.getString("id_film"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(addFilm.class.getName()).log(Level.SEVERE, null, ex);
        }
}        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        film_judul = new javax.swing.JComboBox<>();
        auditorium = new javax.swing.JComboBox<>();
        times = new javax.swing.JTextField();
        dates = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jadwalTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        filmTable = new javax.swing.JTable();
        editBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 236, 72));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myticketing/images/logo.PNG"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel1.setText("Admin Control Panel");

        jPanel3.setBackground(new java.awt.Color(54, 54, 51));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 236, 72));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(54, 54, 51));

        jLabel3.setForeground(new java.awt.Color(255, 236, 79));
        jLabel3.setText("Film :");

        jLabel7.setForeground(new java.awt.Color(255, 236, 79));
        jLabel7.setText("Date :");

        jLabel8.setForeground(new java.awt.Color(255, 236, 79));
        jLabel8.setText("Time :");

        jLabel4.setForeground(new java.awt.Color(255, 236, 79));
        jLabel4.setText("Auditorium :");

        addBtn.setBackground(new java.awt.Color(54, 54, 51));
        addBtn.setForeground(new java.awt.Color(255, 236, 79));
        addBtn.setText("Add!");
        addBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 236, 79), 2, true));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        film_judul.setBackground(new java.awt.Color(54, 54, 51));
        film_judul.setForeground(new java.awt.Color(255, 236, 79));
        film_judul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                film_judulActionPerformed(evt);
            }
        });

        auditorium.setBackground(new java.awt.Color(54, 54, 51));
        auditorium.setForeground(new java.awt.Color(255, 236, 79));
        auditorium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auditoriumActionPerformed(evt);
            }
        });

        times.setBackground(new java.awt.Color(54, 54, 51));
        times.setForeground(new java.awt.Color(255, 236, 79));
        times.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 236, 79), 2, true));

        dates.setBackground(new java.awt.Color(54, 54, 51));
        dates.setForeground(new java.awt.Color(255, 236, 79));
        dates.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 236, 79), 2, true));

        jadwalTable.setBackground(new java.awt.Color(54, 54, 51));
        jadwalTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 236, 79), 2, true));
        jadwalTable.setForeground(new java.awt.Color(255, 236, 79));
        jadwalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jadwalTable.setEnabled(false);
        jadwalTable.setGridColor(new java.awt.Color(54, 54, 51));
        jadwalTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jadwalTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jadwalTable);

        filmTable.setBackground(new java.awt.Color(54, 54, 51));
        filmTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 239, 79), 2, true));
        filmTable.setForeground(new java.awt.Color(255, 239, 79));
        filmTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        filmTable.setEnabled(false);
        filmTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filmTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(filmTable);

        editBtn.setBackground(new java.awt.Color(54, 54, 51));
        editBtn.setForeground(new java.awt.Color(255, 236, 79));
        editBtn.setText("Edit");
        editBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 236, 79), 2, true));
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        delBtn.setBackground(new java.awt.Color(54, 54, 51));
        delBtn.setForeground(new java.awt.Color(255, 236, 79));
        delBtn.setText("Delete");
        delBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 236, 79), 2, true));
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(jLabel8))
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(film_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(dates)
                                .addComponent(auditorium, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(times, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(auditorium, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(times, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dates, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(film_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButton2.setBackground(new java.awt.Color(255, 236, 79));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(54, 54, 51));
        jButton2.setText("Home");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(54, 54, 51), 4, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        id.setEditable(false);
        id.setBackground(new java.awt.Color(54, 54, 51));
        id.setForeground(new java.awt.Color(255, 236, 79));
        id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 236, 79), 1, true));
        id.setDisabledTextColor(new java.awt.Color(255, 236, 79));
        id.setEnabled(false);
        id.setFocusable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.dispose();
        exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        film_id = film_judul.getSelectedItem().toString();
        id_auditorium = auditorium.getSelectedItem().toString();
        timer = times.getText();
        tanggal = dates.getText();
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/selfticket_bioskop", "root", "");
            con.createStatement().executeUpdate("INSERT INTO schedule VALUES (null,'"+film_id+"','"+id_auditorium+"','"+timer+"','"+tanggal+"')");
            JOptionPane.showMessageDialog(null, "Schedule Berhasil Ditambahkan");
        } catch (SQLException ex) {
            Logger.getLogger(addFilm.class.getName()).log(Level.SEVERE, null, ex);
        }
        load_table();
        empty();
    }//GEN-LAST:event_addBtnActionPerformed

    private void film_judulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_film_judulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_film_judulActionPerformed

    private void auditoriumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auditoriumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_auditoriumActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        menuAdmin MA = new menuAdmin();
        MA.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void filmTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filmTableMouseClicked

    }//GEN-LAST:event_filmTableMouseClicked

    private void jadwalTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jadwalTableMouseClicked
        // TODO add your handling code here:
        int row = jadwalTable.rowAtPoint(evt.getPoint());
        String ids = jadwalTable.getValueAt(row, 0).toString();
        String idFilm = jadwalTable.getValueAt(row, 1).toString();
        String idAudi = jadwalTable.getValueAt(row, 2).toString();
        String time = jadwalTable.getValueAt(row, 3).toString();
        String tanggal = jadwalTable.getValueAt(row, 4).toString();
        
        id.setText(ids);
        film_judul.setSelectedItem(idFilm);
        auditorium.setSelectedItem(idAudi);
        times.setText(time);
        dates.setText(tanggal);
    }//GEN-LAST:event_jadwalTableMouseClicked

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        film_id = film_judul.getSelectedItem().toString();
        id_auditorium = auditorium.getSelectedItem().toString();
        timer = times.getText();
        tanggal = dates.getText();
        
        try{
            String sql = "UPDATE schedule SET film_id = '"+film_id+"' , id_auditorium = '"+id_auditorium+"' , time = '"+timer+"' , tanggal = '"+tanggal+"' WHERE id = '"+id.getText()+"'";
            java.sql.Connection conn = (Connection)config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Schedule has been updated!");
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table();
        empty();
    }//GEN-LAST:event_editBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "DELETE FROM schedule WHERE id = '"+id.getText()+"'";
            java.sql.Connection conn = (Connection)config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Schedule has been deleted!");
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table();
        empty();
    }//GEN-LAST:event_delBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addJadwal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JComboBox<String> auditorium;
    private javax.swing.JTextField dates;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JTable filmTable;
    private javax.swing.JComboBox<String> film_judul;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jadwalTable;
    private javax.swing.JTextField times;
    // End of variables declaration//GEN-END:variables

}
