/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wartegque;

import static java.lang.System.exit;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FAIZAL
 */
public class foodController extends javax.swing.JFrame {

    /**
     * Creates new form foodController
     */
    public foodController() {
        initComponents();
        load_table();
        empty();
    }

    private void empty(){
        idInput.setText("");
        menuInput.setText("");
        hargaInput.setText("");
        stokInput.setText("");
        NO.setText("");
    }    
    
    private void load_table(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Id Menu");
        model.addColumn("Menu");
        model.addColumn("Harga");
        model.addColumn("Stok");
        
        try{
          int i = 1;
          String sql = "SELECT * FROM menu";
          java.sql.Connection conn = (Connection)config.configDB();
          java.sql.Statement stm = conn.createStatement();
          java.sql.ResultSet res = stm.executeQuery(sql);
          
          while(res.next()){
              model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5)});
          }
          
          foodTable.setModel(model);
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
          
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transaksiPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        foodBtn = new javax.swing.JPanel();
        foodLabel1 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        foodLabel = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        minBtn6 = new javax.swing.JLabel();
        closeBtn = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        foodTable = new javax.swing.JTable();
        idField = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        idInput = new javax.swing.JTextField();
        menuField = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        menuInput = new javax.swing.JTextField();
        hargaField = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        hargaInput = new javax.swing.JTextField();
        stokField = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        stokInput = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        NO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        transaksiPanel.setBackground(new java.awt.Color(255, 255, 255));

        titlePanel.setBackground(new java.awt.Color(54, 54, 51));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wartegque/images/logo-admin-min.png"))); // NOI18N

        foodBtn.setBackground(new java.awt.Color(30, 30, 30));

        foodLabel1.setBackground(new java.awt.Color(255, 189, 74));
        foodLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        foodLabel1.setForeground(new java.awt.Color(255, 189, 74));
        foodLabel1.setText("Transaksi");
        foodLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout foodBtnLayout = new javax.swing.GroupLayout(foodBtn);
        foodBtn.setLayout(foodBtnLayout);
        foodBtnLayout.setHorizontalGroup(
            foodBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodBtnLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(foodLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        foodBtnLayout.setVerticalGroup(
            foodBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(foodLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel33.setBackground(new java.awt.Color(60, 60, 60));

        foodLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        foodLabel.setForeground(new java.awt.Color(255, 255, 255));
        foodLabel.setText("Foods");
        foodLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(foodLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(foodLabel)
                .addContainerGap())
        );

        jPanel34.setBackground(new java.awt.Color(30, 30, 30));

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(logo)
                .addGap(40, 40, 40))
            .addComponent(foodBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(logo)
                .addGap(26, 26, 26)
                .addComponent(foodBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        minBtn6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        minBtn6.setForeground(new java.awt.Color(255, 189, 74));
        minBtn6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minBtn6.setText("-");
        minBtn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minBtn6MouseClicked(evt);
            }
        });

        closeBtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        closeBtn.setForeground(new java.awt.Color(255, 189, 74));
        closeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeBtn.setText("X");
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });

        jPanel36.setBackground(new java.awt.Color(255, 189, 74));

        jLabel26.setFont(new java.awt.Font("Levenim MT", 1, 20)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Warteg Bahari");

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel26)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 189, 74));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        foodTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 189, 74), 1, true));
        foodTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        foodTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        foodTable.setEnabled(false);
        foodTable.setFocusable(false);
        foodTable.setGridColor(new java.awt.Color(255, 255, 255));
        foodTable.setSelectionBackground(new java.awt.Color(255, 189, 74));
        foodTable.getTableHeader().setResizingAllowed(false);
        foodTable.getTableHeader().setReorderingAllowed(false);
        foodTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(foodTable);

        idField.setBackground(new java.awt.Color(255, 189, 74));
        idField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 189, 74), 1, true));
        idField.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ID");
        idField.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 40, 40));

        idInput.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idInput.setForeground(new java.awt.Color(255, 189, 74));
        idInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 189, 74), 1, true));
        idInput.setCaretColor(new java.awt.Color(255, 189, 74));
        idField.add(idInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 40));

        menuField.setBackground(new java.awt.Color(255, 189, 74));
        menuField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 189, 74), 1, true));
        menuField.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Menu");
        menuField.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 40, 40));

        menuInput.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        menuInput.setForeground(new java.awt.Color(255, 189, 74));
        menuInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 189, 74), 1, true));
        menuInput.setCaretColor(new java.awt.Color(255, 189, 74));
        menuField.add(menuInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 40));

        hargaField.setBackground(new java.awt.Color(255, 189, 74));
        hargaField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 189, 74), 1, true));
        hargaField.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Harga");
        hargaField.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 40, 40));

        hargaInput.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hargaInput.setForeground(new java.awt.Color(255, 189, 74));
        hargaInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 189, 74), 1, true));
        hargaInput.setCaretColor(new java.awt.Color(255, 189, 74));
        hargaField.add(hargaInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 40));

        stokField.setBackground(new java.awt.Color(255, 189, 74));
        stokField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 189, 74), 1, true));
        stokField.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Stok");
        stokField.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 40, 40));

        stokInput.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        stokInput.setForeground(new java.awt.Color(255, 189, 74));
        stokInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 189, 74), 1, true));
        stokInput.setCaretColor(new java.awt.Color(255, 189, 74));
        stokField.add(stokInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 40));

        addBtn.setBackground(new java.awt.Color(255, 255, 255));
        addBtn.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        addBtn.setForeground(new java.awt.Color(0, 153, 0));
        addBtn.setText("Tambah");
        addBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 1, true));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setBackground(new java.awt.Color(255, 255, 255));
        editBtn.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        editBtn.setForeground(new java.awt.Color(255, 189, 74));
        editBtn.setText("Update");
        editBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 189, 74), 1, true));
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(255, 255, 255));
        deleteBtn.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 0, 0));
        deleteBtn.setText("Hapus");
        deleteBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        NO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NO.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true));
        NO.setEnabled(false);

        javax.swing.GroupLayout transaksiPanelLayout = new javax.swing.GroupLayout(transaksiPanel);
        transaksiPanel.setLayout(transaksiPanelLayout);
        transaksiPanelLayout.setHorizontalGroup(
            transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiPanelLayout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transaksiPanelLayout.createSequentialGroup()
                        .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(transaksiPanelLayout.createSequentialGroup()
                                .addGap(351, 351, 351)
                                .addComponent(hargaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(transaksiPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(idField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(menuField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(stokField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(transaksiPanelLayout.createSequentialGroup()
                                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(NO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addComponent(jPanel36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(transaksiPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(minBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        transaksiPanelLayout.setVerticalGroup(
            transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiPanelLayout.createSequentialGroup()
                .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transaksiPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(transaksiPanelLayout.createSequentialGroup()
                        .addComponent(NO, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(menuField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hargaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stokField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 10, Short.MAX_VALUE))))
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transaksiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transaksiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void foodLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodLabelMouseClicked
        // TODO add your handling code here:
        foodController FC = new foodController();
        FC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_foodLabelMouseClicked

    private void minBtn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minBtn6MouseClicked
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_minBtn6MouseClicked

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        // TODO add your handling code here:
        this.dispose();
        exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        String Id_menu, Menu, Harga, Stok, No;
        Id_menu = idInput.getText();
        Menu = menuInput.getText();
        Harga = hargaInput.getText();
        Stok = stokInput.getText();
        No = NO.getText();
          try{
              String sql = "UPDATE menu SET id_menu = '"+Id_menu+"', menu = '"+Menu+"', harga = '"+Harga+"', stok = '"+Stok+"' WHERE no = '"+No+"'";
              java.sql.Connection conn = (Connection)config.configDB();
              java.sql.PreparedStatement pst = conn.prepareStatement(sql);
              pst.execute();
              JOptionPane.showMessageDialog(null, "Menu berhasil diupdate!");
          } catch (Exception e) {
              JOptionPane.showMessageDialog(this, e.getMessage());
          }
          load_table();
          empty();
    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "DELETE FROM menu WHERE no = '"+NO.getText()+"'";
            java.sql.Connection conn = (Connection)config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Menu berhasil dihapus");
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table();
        empty();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        String Id_menu, Menu, Harga, Stok;
        Id_menu = idInput.getText();
        Menu = menuInput.getText();
        Harga = hargaInput.getText();
        Stok = stokInput.getText();
          try{
              String sql = "INSERT INTO menu VALUES (null,'"+Id_menu+"','"+Menu+"','"+Harga+"','"+Stok+"')";
              java.sql.Connection conn = (Connection)config.configDB();
              java.sql.PreparedStatement pst = conn.prepareStatement(sql);
              pst.execute();
              JOptionPane.showMessageDialog(null, "Menu berhasil ditambahkan!");
          } catch (Exception e) {
              JOptionPane.showMessageDialog(this, e.getMessage());
          }
          load_table();
          empty();
    }//GEN-LAST:event_addBtnActionPerformed

    private void foodTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodTableMouseClicked
        // TODO add your handling code here:
        int row = foodTable.rowAtPoint(evt.getPoint());
        String no = foodTable.getValueAt(row, 0).toString();
        String id_menu = foodTable.getValueAt(row, 1).toString();
        String menu = foodTable.getValueAt(row, 2).toString();
        String harga = foodTable.getValueAt(row, 3).toString();
        String stok = foodTable.getValueAt(row, 4).toString();
        
        NO.setText(no);
        idInput.setText(id_menu);
        menuInput.setText(menu);
        hargaInput.setText(harga);
        stokInput.setText(stok);
    }//GEN-LAST:event_foodTableMouseClicked

    private void foodLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodLabel1MouseClicked
        // TODO add your handling code here:
        landingAdmin LA = new landingAdmin();
        LA.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_foodLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(foodController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(foodController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(foodController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(foodController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new foodController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NO;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JPanel foodBtn;
    private javax.swing.JLabel foodLabel;
    private javax.swing.JLabel foodLabel1;
    private javax.swing.JTable foodTable;
    private javax.swing.JPanel hargaField;
    private javax.swing.JTextField hargaInput;
    private javax.swing.JPanel idField;
    private javax.swing.JTextField idInput;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel menuField;
    private javax.swing.JTextField menuInput;
    private javax.swing.JLabel minBtn6;
    private javax.swing.JPanel stokField;
    private javax.swing.JTextField stokInput;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JPanel transaksiPanel;
    // End of variables declaration//GEN-END:variables
}
