/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
/**
 *
 * @author FAIZAL
 */
public class form extends javax.swing.JFrame {
String firstname_get, lastname_get, fullname_get, religion_get, gender_get, dob_get, address_get, phone_get;
    /**
     * Creates new form form
     */
    public form() {
        initComponents();
        clear();
        firstname.setFocusable(true);        
    }
    
    public void clear(){
        firstname.setText("First name");
        lastname.setText("Last name");
        phone_input.setText("Phone number");
        address_input.setText("Address");
        Rel_input.setText("Religion");
        dob_input.setCalendar(null);
        ButtonGroup options = new ButtonGroup( );
        options.add(radopt_1);
        options.add(radopt_2);
        options.add(radopt_3);
        options.clearSelection();    
    }
    
    private void prepare(){
        //Fullname
        firstname_get = firstname.getText();
        lastname_get = lastname.getText();
        fullname_get = firstname_get+" "+lastname_get;
        
        //Gender
        if(radopt_1.isSelected()){
            gender_get = "Man";
        }
        else if(radopt_2.isSelected()){
            gender_get = "Woman";
        }
        else if(radopt_3.isSelected()){
            gender_get = "Not Defined";
        }
        
        //Religion
        religion_get = Rel_input.getText();
        
        //Date of Birth
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        dob_get = sdf.format(dob_input.getDate());
        
        //Address
        address_get = address_input.getText();
        
        //Phone Number
        phone_get = phone_input.getText();
    }
    
    public void add(){
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/pbo", "root", "");
            con.createStatement().executeUpdate("INSERT INTO biodata VALUES (null ,'"+fullname_get+"','"+gender_get+"','"+religion_get+"','"+dob_get+"', '"+address_get+"', '"+phone_get+"')");
            JOptionPane.showMessageDialog(this, "Data has successdully been added!");
            clear();
        } catch (SQLException ex) {
            Logger.getLogger(form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void minimize(){
        this.setState(ICONIFIED);
    }
    
    private void close(){
        this.dispose();
        System.exit(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        address_input = new javax.swing.JTextArea();
        phone_input = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        radopt_3 = new javax.swing.JRadioButton();
        radopt_2 = new javax.swing.JRadioButton();
        radopt_1 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        dob_input = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Rel_input = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyBiodata v.1.1");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(7, 132, 181), 2, true));

        jPanel2.setBackground(new java.awt.Color(7, 132, 181));

        jLabel1.setFont(new java.awt.Font("Geometr231 Hv BT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Form Biodata");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("-");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        firstname.setColumns(30);
        firstname.setFont(new java.awt.Font("Levenim MT", 0, 12)); // NOI18N
        firstname.setText("First name");
        firstname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(57, 172, 231), 1, true));
        firstname.setCaretColor(new java.awt.Color(57, 172, 231));
        firstname.setMargin(new java.awt.Insets(2, 4, 2, 2));
        firstname.setNextFocusableComponent(lastname);
        firstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnameFocusLost(evt);
            }
        });
        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });

        lastname.setFont(new java.awt.Font("Levenim MT", 0, 12)); // NOI18N
        lastname.setText("Last name");
        lastname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(57, 172, 231), 1, true));
        lastname.setCaretColor(new java.awt.Color(57, 172, 231));
        lastname.setMargin(new java.awt.Insets(2, 4, 2, 2));
        lastname.setNextFocusableComponent(radopt_1);
        lastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastnameFocusLost(evt);
            }
        });

        address_input.setColumns(20);
        address_input.setFont(new java.awt.Font("Levenim MT", 0, 12)); // NOI18N
        address_input.setRows(5);
        address_input.setText("Address");
        address_input.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(57, 172, 231), 1, true));
        address_input.setCaretColor(new java.awt.Color(57, 172, 231));
        address_input.setNextFocusableComponent(phone_input);
        address_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                address_inputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                address_inputFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(address_input);

        phone_input.setFont(new java.awt.Font("Levenim MT", 0, 12)); // NOI18N
        phone_input.setText("Phone number");
        phone_input.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(57, 172, 231), 1, true));
        phone_input.setCaretColor(new java.awt.Color(57, 172, 231));
        phone_input.setNextFocusableComponent(jButton1);
        phone_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phone_inputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phone_inputFocusLost(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 168, 37));
        jButton1.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.setBorder(null);
        jButton1.setNextFocusableComponent(firstname);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gender", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Levenim MT", 0, 14), new java.awt.Color(57, 172, 231))); // NOI18N

        radopt_3.setBackground(new java.awt.Color(255, 255, 255));
        radopt_3.setFont(new java.awt.Font("Levenim MT", 0, 12)); // NOI18N
        radopt_3.setForeground(new java.awt.Color(57, 172, 231));
        radopt_3.setText("Rather not say");
        radopt_3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(57, 172, 231), 1, true));
        radopt_3.setNextFocusableComponent(dob_input);

        radopt_2.setBackground(new java.awt.Color(255, 255, 255));
        radopt_2.setFont(new java.awt.Font("Levenim MT", 0, 12)); // NOI18N
        radopt_2.setForeground(new java.awt.Color(57, 172, 231));
        radopt_2.setText("Woman");
        radopt_2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(57, 172, 231), 1, true));
        radopt_2.setNextFocusableComponent(radopt_3);

        radopt_1.setBackground(new java.awt.Color(255, 255, 255));
        radopt_1.setFont(new java.awt.Font("Levenim MT", 0, 12)); // NOI18N
        radopt_1.setForeground(new java.awt.Color(57, 172, 231));
        radopt_1.setText("Man");
        radopt_1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(57, 172, 231), 1, true));
        radopt_1.setNextFocusableComponent(radopt_2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(radopt_1)
                .addGap(32, 32, 32)
                .addComponent(radopt_2)
                .addGap(32, 32, 32)
                .addComponent(radopt_3)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radopt_1)
                    .addComponent(radopt_2)
                    .addComponent(radopt_3))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(57, 172, 231));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(57, 172, 231), 2, true));

        dob_input.setBackground(new java.awt.Color(255, 255, 255));
        dob_input.setNextFocusableComponent(address_input);

        jLabel2.setFont(new java.awt.Font("Levenim MT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DOB");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dob_input, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(dob_input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel5.setBackground(new java.awt.Color(30, 174, 152));
        jLabel5.setFont(new java.awt.Font("Geometr231 BT", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 174, 152));
        jLabel5.setText("@coderilla__");

        Rel_input.setFont(new java.awt.Font("Levenim MT", 0, 12)); // NOI18N
        Rel_input.setText("Religion");
        Rel_input.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(7, 132, 181), 1, true));
        Rel_input.setCaretColor(new java.awt.Color(7, 132, 181));
        Rel_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Rel_inputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Rel_inputFocusLost(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(229, 0, 11));
        jButton2.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Clear");
        jButton2.setBorder(null);
        jButton2.setNextFocusableComponent(firstname);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(phone_input, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lastname))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(128, 128, 128))
                    .addComponent(Rel_input))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Rel_input, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone_input, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        prepare();
        add();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void firstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameFocusGained
        // TODO add your handling code here:
        if(firstname.getText().equals("First name")){
            firstname.setText("");
        }
        
    }//GEN-LAST:event_firstnameFocusGained

    private void firstnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameFocusLost
        // TODO add your handling code here:
        if(firstname.getText().equals("")){
            firstname.setText("First name");
        }
        
    }//GEN-LAST:event_firstnameFocusLost

    private void lastnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameFocusGained
        // TODO add your handling code here:
        if(lastname.getText().equals("Last name")){
            lastname.setText(""); 
        }
        
    }//GEN-LAST:event_lastnameFocusGained

    private void lastnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameFocusLost
        // TODO add your handling code here:
        if(lastname.getText().equals("")){
            lastname.setText("Last name");
        }        
    }//GEN-LAST:event_lastnameFocusLost

    private void address_inputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_address_inputFocusGained
        // TODO add your handling code here:
        if(address_input.getText().equals("Address")){
            address_input.setText("");
        }  
    }//GEN-LAST:event_address_inputFocusGained

    private void address_inputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_address_inputFocusLost
        // TODO add your handling code here:
        if(address_input.getText().equals("")){
            address_input.setText("Address");
        } 
    }//GEN-LAST:event_address_inputFocusLost

    private void phone_inputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phone_inputFocusGained
        // TODO add your handling code here:
        if(phone_input.getText().equals("Phone number")){
            phone_input.setText("");
        }  
    }//GEN-LAST:event_phone_inputFocusGained

    private void phone_inputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phone_inputFocusLost
        // TODO add your handling code here:
        if(phone_input.getText().equals("")){
            phone_input.setText("Phone number");
        } 
    }//GEN-LAST:event_phone_inputFocusLost

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        minimize();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void Rel_inputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Rel_inputFocusGained
        // TODO add your handling code here:
        if(Rel_input.getText().equals("Religion")){
            Rel_input.setText("");
        }  
    }//GEN-LAST:event_Rel_inputFocusGained

    private void Rel_inputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Rel_inputFocusLost
        // TODO add your handling code here:
        if(Rel_input.getText().equals("")){
            Rel_input.setText("Religion");
        }
    }//GEN-LAST:event_Rel_inputFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Rel_input;
    private javax.swing.JTextArea address_input;
    private com.toedter.calendar.JDateChooser dob_input;
    private javax.swing.JTextField firstname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField phone_input;
    private javax.swing.JRadioButton radopt_1;
    private javax.swing.JRadioButton radopt_2;
    private javax.swing.JRadioButton radopt_3;
    // End of variables declaration//GEN-END:variables
}
